ts: Add functionality to subscribe to all program accounts.
coral-xyz/anchor pull request #1306
Opened 2022-01-12 18:37 UTC by xjcaa

Draft implementation.

#1305 Adds the functionality mentioned in here.

2022-01-12 18:56 UTC, armaniferrante commented
I think the slot context information is dropped by the underlying web3.js library. Might need to plumb into that package.

2022-01-14 05:39 UTC, xjcaa commented
The `AccountChangeCallback` and `ProgramAccountChangeCallback` both pass back the context. See https://github.com/solana-labs/solana-web3.js/blob/master/src/connection.ts#L1753-L1756

2022-01-14 16:16 UTC, armaniferrante commented on ts/src/program/namespace/account.ts
> +          memcmp: {
This should be `this.coder.memcmp(this._idlAcocunt.name),`. The program client no longer assumes a borsh coder.

2022-01-14 16:16 UTC, armaniferrante requested changes
Needs a coder update

2024-08-28 13:22 UTC, closed without merging

2024-08-28 13:22 UTC, armaniferrante commented
Closing as stale.