Add exploits to docs
coral-xyz/anchor pull request #2041
Opened 2022-07-07 19:07 UTC by nheingit

In the process of adding the contents of: https://github.com/coral-xyz/sealevel-attacks to the docs.

This PR will add all of the exploits, as well as describe them in detail, instead of providing just the code.

# progress

- [x] - signer authorization
- [x] account data matching
- [ ] - owner checks
- [ ] - type cosplay
- [ ] - initialization
- [ ] - arbitrary cpi
- [ ] - duplicate mutable accounts
- [ ] - bump seed canonicalization
- [ ] - pda sharing
- [ ] - Closing accounts

2022-07-13 18:57 UTC, italoacasas commented
Amazing contribution. 

I wonder if the first section called "Sealevel Attacks" is redundant now that we have independent articles. 

cc @armaniferrante wdyt?

2022-07-13 19:01 UTC, italoacasas commented
@nheingit, you can see all the new pages in your dev env? 

I can't see some in the [test deployment](https://anchor-docs-git-fork-nheingit-add-exploits-to-docs-200ms.vercel.app/docs/signer-authorization-exploit)

2022-07-13 19:10 UTC, nheingit commented
Weird.

Yeah I can see them on mine:

![Screen Shot 2022-07-13 at 2 09 29 PM](https://user-images.githubusercontent.com/60185486/178812619-0f20f041-b13f-4ec5-822e-beb5fc8a8476.png)

2022-07-20 15:57 UTC, nheingit commented
@italoacasas any idea why the tests are failing here? I can't tell what Clippy would be having problems with here...

2022-07-20 16:08 UTC, italoacasas commented
No idea, but I doubt it's related to this PR.

2022-07-20 16:46 UTC, nheingit commented
Okay cool, then I won't worry about it 👍 

Unrelated to this PR, but don't really want to open an issue for it.

Would I be able to open a PR if I wrote a guide on an updated version of the `escrow-program`? I was going to put it on my blog, but thought it could live here under the `proejcts` instead.

Didn't know what kind of review process that would take, or if y'all were interested in having more "anchor approved" projects up on the site.

2022-07-20 17:15 UTC, italoacasas commented
> Would I be able to open a PR if I wrote a guide on an updated version of the `escrow program`? I was going to put it on my blog but thought it could live here under the `projects` instead.

It sounds like a good idea.

> Didn't know what kind of review process that would take, or if y'all were interested in having more "anchor approved" projects up on the site.

Historically the escrow program has been an excellent example for learning to use anchor/Solana. Go for it.

2022-07-22 21:18 UTC, ashpoolin commented on docs/src/pages/docs/owner-checks-exploit.md
> +When the owner is not who you expect it to be, your program's data can change beneth you unexpectedly, or grant un-intended privledges to a rogue actor.
```suggestion
When the owner is not who you expect it to be, your program's data can change beneath you unexpectedly, or grant unintended privileges to a rogue actor.
```

2022-07-22 21:23 UTC, ashpoolin commented on docs/src/pages/docs/type-cosplay-exploit.md
> +The type cosplay vulnerability is when your program does not properly identify the account you are working with
```suggestion
The type cosplay vulnerability is when your program does not properly identify the account you are working with.
```

2022-07-22 21:24 UTC, ashpoolin commented on docs/src/pages/docs/type-cosplay-exploit.md
> +This code is insecure because the `User` account and the `Metadata` account could be used interchangaby in this code.
```suggestion
This code is insecure because the `User` account and the `Metadata` account could be used interchangeably in this code.
```

2022-07-22 21:28 UTC, ashpoolin commented on docs/src/pages/docs/initialization-exploit.md
> +Another side effect of this, is that you could call initialize on an already-existing account.
```suggestion
Another side effect of this, is that you could call initialize on an already existing account.
```

2022-07-22 21:31 UTC, ashpoolin commented on docs/src/pages/docs/arbitrary-cpi-exploit.md
> +The arbitrary cpi vulnerability is when your program does not properly validate the programm that it is invoking.
```suggestion
The arbitrary CPI vulnerability is when your program does not properly validate the program that it is invoking.
```

2022-07-22 21:33 UTC, ashpoolin commented on docs/src/pages/docs/arbitrary-cpi-exploit.md
> +Any data that is inputted by a user needs to be validated.
```suggestion
Any data that is entered by a user needs to be validated.
```

2022-07-22 21:37 UTC, ashpoolin commented on docs/src/pages/docs/arbitrary-cpi-exploit.md
> +While Anchor has an already existing wrapper for the SPL token program, you can see how to implement this yourself for other non-anchor programs that you want to interact with [here](https://docs.rs/
```suggestion
While Anchor has an already existing wrapper for the SPL token program, you can see how to implement this yourself for other non-Anchor programs that you want to interact with [here](https://docs.rs/anchor-lang/latest/anchor_lang/accounts/account/struct.Account.html#using-account-with-non-anchor-programs).
```

2022-07-22 21:37 UTC, ashpoolin commented on docs/src/pages/docs/duplicate-mutable-accounts-exploit.md
> +When you do not properly validate these inputs, you could have unintended concequences.
```suggestion
When you do not properly validate these inputs, you could have unintended consequences.
```

2022-07-22 21:39 UTC, ashpoolin commented on docs/src/pages/docs/duplicate-mutable-accounts-exploit.md
> +With this check in place, we can be sure that the two accounts are seperate before we move forward.
```suggestion
With this check in place, we can be sure that the two accounts are separate before we move forward.
```

2022-07-22 21:45 UTC, ashpoolin commented on docs/src/pages/docs/pda-sharing-exploit.md
> +The PDA sharing exploit occurs whenever a program uses one PDA as an authority for multiple "sources".
```suggestion
The PDA sharing exploit occurs whenever a program uses one PDA as an authority for multiple "sources."
```

2022-07-22 21:54 UTC, ashpoolin commented on docs/src/pages/docs/closing-accounts-exploit.md
> +## Overview
No editorial / commentary in this one yet?

2022-07-22 21:57 UTC, ashpoolin commented
Great job, Noah! As best as I can tell the examples are correct, so my suggestions are purely fixes for spelling, grammar, and typos. I even learned a few things while reviewing...

2022-07-24 14:14 UTC, nheingit commented on docs/src/pages/docs/closing-accounts-exploit.md
> +## Overview
correct, this is a bit above my pay-grade. I think it's still helpful to have all the code readable though.

2022-08-04 17:09 UTC, nheingit commented
Thanks for the review @ashpoolin !

@italoacasas is there anything else I need to do to get this merged in?

2022-08-04 18:17 UTC, italoacasas commented
@nheingit, my plate is a little insane right now, but I will start reviewing the content tonight. Either way, I'm not an expert on the exploits. cc @armaniferrante

2022-08-04 18:22 UTC, nheingit commented
Don't want it to cause any undue stress! Just wanted to bump this since it had been a little bit. Happy to hop on a call or anything to help. You have me on Twitter I think, and my tg handle is the same if you want to kick off any discussion there.

2022-08-18 12:27 UTC, swimricky commented on docs/src/pages/docs/bump-seed-canonicalization-exploit.md
> +    // 2) using the account via `#[account(init, seeds = [...], bump = data.bump)]
if using the account then there shouldn't be an `init` in the `#[account()]` right?

2022-08-20 03:04 UTC, nheingit commented on docs/src/pages/docs/bump-seed-canonicalization-exploit.md
> +    // 2) using the account via `#[account(init, seeds = [...], bump = data.bump)]
That sounds right to me. if you suggest a change I'll commit it.

2022-08-20 14:37 UTC, callensm requested changes

2022-08-20 14:37 UTC, callensm commented on docs/src/pages/docs/bump-seed-canonicalization-exploit.md
> +    // 2) using the account via `#[account(init, seeds = [...], bump = data.bump)]
```suggestion
    // 2) using the account via `#[account(seeds = [...], bump = data.bump)]
```

2022-09-03 18:33 UTC, nheingit commented
ping @callensm

2022-12-06 16:28 UTC, Henry-E commented
Bloody hell, this rebase thing is a mess, sorry about this. it's harder to fix this particular mess since somehow git has snuck in extra commits between commit: cb46474c38d1a7137e919d35c6dff57ea4b06fb1  and commit: 0101d583b830868692ccea4d818bc24c54574f5b . 

Sorry to leave this mess here but i have to run right now. When I get back i will revert back to commit 0101d583b830868692ccea4d818bc24c54574f5b and pick out the extra random commits that git added in.

Maybe then the rebasing will work properly.

2022-12-06 17:10 UTC, Henry-E commented
Just trying to authorize the vercel deployment so that I can more easily read through and actually check out what this PR is adding in.

2022-12-07 10:30 UTC, Henry-E commented
Upon further reflection I think this just highlights that the anchor site needs a better way to curate and link to relevant blog posts. That way we can keep the main site mostly clean and help people by linking out where needed. For example to all of the great blog posts written by nheingit.

2022-12-14 14:06 UTC, nheingit commented
Just now seeing these @Henry-E

Linking out would be fine. But I only put them up on my site after seeing coral wasn't going to merge this.

2022-12-14 19:52 UTC, Henry-E commented
ah ok cool, sorry about the lack of communication. Thanks for posting them on your blog anyway!

2022-12-14 19:52 UTC, closed without merging